### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by roncewind** [Senzing/docker-g2loader#54]
update to use Debian base

**Comment by docktermj** [comment]
Add a `Dockerfile` to https://github.com/Senzing/g2loader and deprecate this repository.

**Comment by docktermj** [comment]
Deprecating using the instructions at https://github.com/Senzing/knowledge-base/blob/main/HOWTO/deprecate-a-github-repository.md

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/docker-g2loader/pull/63
